// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxLvkmKE2Zr05aiptM32sgEAyDCwUlDX0',
    appId: '1:888954179624:web:b643d81ddd8b43d359e51d',
    messagingSenderId: '888954179624',
    projectId: 'thread-astronuts-abc',
    authDomain: 'thread-astronuts-abc.firebaseapp.com',
    storageBucket: 'thread-astronuts-abc.appspot.com',
    measurementId: 'G-4SZCLNL9WQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC6WH942zCnlR6p0oLym4CAso0Jvr43QA',
    appId: '1:888954179624:android:1b2981b71047fe2059e51d',
    messagingSenderId: '888954179624',
    projectId: 'thread-astronuts-abc',
    storageBucket: 'thread-astronuts-abc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-4841C9or5VEPx90e9vWwdLemd9Y0FRA',
    appId: '1:888954179624:ios:c0524b4ca7a14cdf59e51d',
    messagingSenderId: '888954179624',
    projectId: 'thread-astronuts-abc',
    storageBucket: 'thread-astronuts-abc.appspot.com',
    iosBundleId: 'com.example.astronuts',
  );
}
